### ISSUE TITLE
[Feature Request]: Set state to "undefined" if price is 0

### ISSUE THREAD

**Issue by j-loewen** [firstof9/ha-gasbuddy#103]
### The feature

I live rural and in my area there are not many people who report the prices to GasBuddy so I see very often the price drop to 0. I think it would be better to have the state turn to undefined in that case. If it would be "undefined" it would not look wrong on a graph and it would make it easier to make an automation where you're trying to detect a price drop.

**Comment by firstof9** [comment]
I'll see what I can do.

**Comment by firstof9** [comment]
This should be working in [1.0.15-b0](https://github.com/firstof9/ha-gasbuddy/releases/tag/1.0.15-b0) please give it a test.

**Comment by j-loewen** [comment]
It looks good. It now shows "undefined" instead of 0.00

**Comment by firstof9** [comment]
Can you confirm your sensor shows it as "unavailable" in HA?

**Comment by j-loewen** [comment]
Yes, they do. 
![Screenshot_20241018_144846_Home Assistant](https://github.com/user-attachments/assets/75e14ee4-e0dc-405c-bfd1-2b0ede14f7bd)

**Comment by brunob45** [comment]
I just installed the beta version, works for me too! ![Screenshot_20241018-173219.png](https://github.com/user-attachments/assets/57638043-bd29-4cac-88a7-7d83ade8c57b)

**Comment by firstof9** [comment]
Thanks everyone.
