### ISSUE TITLE
[Feature Request]: Disable/remove locations

### ISSUE THREAD

**Issue by VACIndustries** [firstof9/ha-gasbuddy#121]
### The feature

Would love a feature to remove the locations/mapping.  They appear on the HA map and it's kinda annoying (thought you could do this with any entity/device but apparently not)

Regardless awesome work! Thank you!

**Comment by firstof9** [comment]
Added in [1.0.17-b3](https://github.com/firstof9/ha-gasbuddy/releases/tag/1.0.17-b3) feedback would be great.
Thanks.

**Comment by VACIndustries** [comment]
@firstof9 perfect! Thank you!
