### ISSUE TITLE
Gallons/Liters not needed

### ISSUE THREAD

**Issue by tmcb82** [firstof9/ha-gasbuddy#13]
Is there a way we can remove the "gallon" or "liter" from the display (ex. 2.89 USD **/gallon)** as it is universally known that the United States is gallons and most everywhere else is liters? This add clutter to cards.

Thank you for your consideration.

**Comment by firstof9** [comment]
I'll see what I can do.

**Comment by tmcb82** [comment]
> I'll see what I can do.

Thank you kindly

**Comment by firstof9** [comment]
I've added a toggle to the options in `1.0.4`, keep an eye out for the release.
