### ISSUE TITLE
New liter/gallon toggle doesn’t work

### ISSUE THREAD

**Issue by tmcb82** [firstof9/ha-gasbuddy#16]
I enable it and it says operation successful but it doesn’t change and when you open the menu it is checked again. I tried rebooting and uninstalling and re installing. Sorry to bother again and thank you Chris!

**Comment by firstof9** [comment]
No worries, I'll take a look.

**Comment by tmcb82** [comment]
Here's my diagnostic if that helps

"gasbuddy": {
      "version": "1.0.4",
      "requirements": [
        "py-gasbuddy==0.2.3"
      ]
    }
  },
  "integration_manifest": {
    "domain": "gasbuddy",
    "name": "GasBuddy",
    "codeowners": [
      "@firstof9"
    ],
    "config_flow": true,
    "documentation": "https://github.com/firstof9/ha-gasbuddy",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/firstof9/ha-gasbuddy/issues",
    "requirements": [
      "py-gasbuddy==0.2.3"
    ],
    "version": "1.0.4",
    "is_built_in": false
  },
  "data": {
    "station_id": "Removed for privacy",
    "unit_of_measure": "dollars_per_gallon",
    "currency": "USD",
    "regular_gas": {
      "credit": "dewman810",
      "price": 2.78,
      "last_updated": "2023-12-13T23:15:03.440Z"
    },
    "midgrade_gas": {
      "credit": "elf_jr",
      "price": 3.28,
      "last_updated": "2023-12-14T04:10:29.325Z"
    },
    "premium_gas": {
      "credit": "elf_jr",
      "price": 3.78,
      "last_updated": "2023-12-14T04:10:29.372Z"
    },
    "diesel": {
      "credit": "elf_jr",
      "price": 4.19,
      "last_updated": "2023-12-14T04:10:29.388Z"
    }
  }
}

**Comment by firstof9** [comment]
Can you go to the :hammer:  -> States menu in HA and find the gas sensor and see what the "unit_of_measure" is saying?

**Comment by tmcb82** [comment]
<img width="897" alt="Screenshot 2023-12-14 091141" src="https://github.com/firstof9/ha-gasbuddy/assets/9359988/9ea7bc55-41bf-4491-bd03-abdf215f2477">

**Comment by firstof9** [comment]
Fixed in `1.0.5` keep an eye out for the release.
I've tested it manually so I know it works. It does produce a false error about unique IDs but you can ignore that.

**Comment by tmcb82** [comment]
Thank you very much!

**Comment by tmcb82** [comment]
It works perfectly. No ID error either.
