### ISSUE TITLE
Add last time updated?

### ISSUE THREAD

**Issue by Basicallyapenguin** [firstof9/ha-gasbuddy#23]
Hey! Loving the addon for home assistant was wondering if it would be possible to pull in the last time the price was updated? Not sure were to put this since it's not an "issue" so sorry for that but though it would be a cool addition!

**Comment by firstof9** [comment]
This is already implemented, it's an attribute of the sensor entity.

**Comment by Basicallyapenguin** [comment]
Ahhh I see it now. I was looking at the home assistant last update which is showing longer, I see the sensor entity now. Thanks for the quick reply!
