### ISSUE TITLE
Refuses to install

### ISSUE THREAD

**Issue by lordwizzard** [firstof9/ha-gasbuddy#26]
The repository shows up using the custom repository, but can't "download" fails. There is no "install button". A restart of HA just wipes everything for it out. Just loops around all the times I've tried it. 

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:730
Integration: HACS (documentation, issues)
First occurred: 3:40:35 PM (1 occurrences)
Last logged: 3:40:35 PM

Download failed - Got status code 404 when trying to download https://github.com/firstof9/ha-gasbuddy/releases/download/1.0.5/gasbuddy.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 730, in async_download_file
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/firstof9/ha-gasbuddy/releases/download/1.0.5/gasbuddy.zip

Also:

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:986
Integration: HACS (documentation, issues)
First occurred: 3:40:35 PM (1 occurrences)
Last logged: 3:40:35 PM

<Integration firstof9/ha-gasbuddy> Failed to download https://github.com/firstof9/ha-gasbuddy/releases/download/tags/1.0.5/gasbuddy.zip

**Comment by firstof9** [comment]
What's the error message in `home-assistant.log` say?

**Comment by lordwizzard** [comment]
Just added the log messages see top post

**Comment by lordwizzard** [comment]
Also this from log:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/repositories/base.py:990
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 3:40:35 PM (1 occurrences)
Last logged: 3:40:35 PM

[547257660736] Error handling message: Unknown error (unknown_error) RA Kish from 192.168.1.32 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 893, in async_install
    await self.async_install_repository(version=version)
  File "/config/custom_components/hacs/repositories/base.py", line 990, in async_install_repository
    raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details

**Comment by firstof9** [comment]
Please verify and if it's working, please close your issue. Thanks!

**Comment by lordwizzard** [comment]
It is now working correctly from the download, adding integration, and configuring. Thank you
