### ISSUE TITLE
[Feature Request]: Display price for cash

### ISSUE THREAD

**Issue by neilbrookins** [firstof9/ha-gasbuddy#67]
### The feature

The current prices are only showing for credit card purchases. Its not currently displaying the cash price which is often cheaper. It would be nice to have an option to toggle on the cash price display too. By default it should be not shown because the standard behavior for Gas Buddy is to show credit price. But the option to unhide it should be possible.

**Comment by firstof9** [comment]
Do you have an example of a location with cash pricing?

**Comment by neilbrookins** [comment]
https://www.gasbuddy.com/station/205033
The above in Collegeville PA has cash.
