### ISSUE TITLE
[Bug]: New stations are named with device id rather than device name

### ISSUE THREAD

**Issue by FireFingers21** [firstof9/ha-gasbuddy#70]
### The problem

When adding a new station and entering the name `Gas Station`, the device name is set to `gas_station` which is not what I typed. I then have to manually rename the device a second time for it to finally display as `Gas Station`.

### What version of Home Assistant?

core-2024.9.1

### What version of GasBuddy?

1.0.9

**Comment by firstof9** [comment]
Should be fixed in `1.0.10`
Thanks!
