### ISSUE TITLE
[Feature Request]: Option to Enable/Disable Fuels/Grades/Cash During Configuration

### ISSUE THREAD

**Issue by foreverimagining** [firstof9/ha-gasbuddy#82]
### The feature

I would like to have added to the configuration flow the option to enable or disable the different fuels, grades, and cash entities so that I don't have to go through and manually disable them from the device page. 

I personally am only interested in regular gas, and the stations that I am checking don't seem to have a cheaper cash option, or I won't be using it, so there is no need for the excess entities to be enabled. Having a series of check marks to choose the fuels, grades, and cash options at setup would be much more expedient than having them all enabled by default.

**Comment by firstof9** [comment]
I think it would be easier to have the extra sensors disabled by default and have the user's enable them as they see fit.

**Comment by foreverimagining** [comment]
That would probably be easiest to implement. I was just figuring that not everyone would have a primary interest in, say, regular gas, so being able to choose during configuration would prevent other people from having to go through the reverse, manually enabling each fuel/grade/cash that they are interested in and disabling the default if they're not.

**Comment by firstof9** [comment]
I'll likely keep the 3 main grades enabled by default and everything else disabled by default, including the cash prices.

**Comment by foreverimagining** [comment]
I'll leave it up to your preference. Either way, it'll be less additional work for me if I need to add more stations in the future, so I will find it beneficial. Thank you for your time and consideration.

**Comment by firstof9** [comment]
This has been added in [1.0.13-b0](https://github.com/firstof9/ha-gasbuddy/releases/tag/1.0.13-b0)
