### ISSUE TITLE
[Feature Request]: Add More Gas Types

### ISSUE THREAD

**Issue by jrstough** [firstof9/ha-gasbuddy#83]
### The feature

Add E85 and UNL88.  These are two more grades of gas sold in my area Zip code 17366

**Comment by firstof9** [comment]
I'll take a look at the API response and see what I can do.

**Comment by firstof9** [comment]
This has been added in [1.0.13-b0](https://github.com/firstof9/ha-gasbuddy/releases/tag/1.0.13-b0), please test it. Thanks.
