### ISSUE TITLE
[Bug]: All gas prices show $0.00

### ISSUE THREAD

**Issue by JohnyBeGood** [firstof9/ha-gasbuddy#99]
### The problem

Hi,

Thanks for developing this integration!

It worked fine until this morning. Out of nowhere it shows $0.00. I checked on the GasBuddy website and there was price there. I also removed everything including the gas station and added again, but that did not made any difference.
Not sure if new version broke it or what.

### What version of Home Assistant?

core-2024.10.1

### What version of GasBuddy?

1.0.14

### Diagnostics information

![Screenshot 2024-10-10 113541](https://github.com/user-attachments/assets/8440e1d5-9da0-4823-8c65-7cee13f38a9e)

**Comment by firstof9** [comment]
What's the station ID?

**Comment by firstof9** [comment]
The API's reporting 0 as the price:

```json
{
    "data": {
        "station": {
            "brands": [
                {
                    "imageUrl": "https://images.gasbuddy.io/b/56.png"
                },
                {
                    "imageUrl": "https://images.gasbuddy.io/b/56.png"
                }
            ],
            "prices": [
                {
                    "cash": null,
                    "credit": {
                        "nickname": null,
                        "postedTime": null,
                        "price": 0
                    },
                    "fuelProduct": "regular_gas",
                    "longName": "Regular"
                },
                {
                    "cash": null,
                    "credit": {
                        "nickname": null,
                        "postedTime": null,
                        "price": 0
                    },
                    "fuelProduct": "midgrade_gas",
                    "longName": "Midgrade"
                },
                {
                    "cash": null,
                    "credit": {
                        "nickname": null,
                        "postedTime": null,
                        "price": 0
                    },
                    "fuelProduct": "premium_gas",
                    "longName": "Premium"
                },
                {
                    "cash": null,
                    "credit": {
                        "nickname": null,
                        "postedTime": null,
                        "price": 0
                    },
                    "fuelProduct": "diesel",
                    "longName": "Diesel"
                }
            ],
            "priceUnit": "dollars_per_gallon",
            "currency": "USD",
            "id": "156618",
            "latitude": 47.364016302532,
            "longitude": -122.020983695983
        }
    }
}
```

**Comment by firstof9** [comment]
Maybe they requested their prices be wiped?

**Comment by JohnyBeGood** [comment]
> Maybe they requested their prices be wiped?

Possible, but I doubt it as other not related stations in radius do not have prices listed. 
Really odd. I wonder if something is going on with their system.

**Comment by JohnyBeGood** [comment]
Closing this as it appears to be an issue with GasBuddy and not this integration.

**Comment by brunob45** [comment]
@JohnyBeGood
@firstof9 thanks for the integration! I'm trying to keep track of the trends of the gas prices, but the "free" gas is quite annoying... Seems like the API is reporting 0$ when it's "not available". To better reflect that, could it be possible to make the entity "offline" when price is 0$?
Thanks!
![image](https://github.com/user-attachments/assets/882ea63e-183c-40bd-a73c-8776abd95962)

**Comment by firstof9** [comment]
> could it be possible to make the entity "offline" when price is 0$?

Can you open a feature request for this for me please for tracking?

**Comment by JohnyBeGood** [comment]
> @JohnyBeGood @firstof9 thanks for the integration! I'm trying to keep track of the trends of the gas prices, but the "free" gas is quite annoying... Seems like the API is reporting 0$ when it's "not available". To better reflect that, could it be possible to make the entity "offline" when price is 0$? Thanks! ![image](https://private-user-images.githubusercontent.com/21108660/377702432-882ea63e-183c-40bd-a73c-8776abd95962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNzEyNjUsIm5iZiI6MTcyOTI3MDk2NSwicGF0aCI6Ii8yMTEwODY2MC8zNzc3MDI0MzItODgyZWE2M2UtMTgzYy00MGJkLWE3M2MtODc3NmFiZDk1OTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE3MDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NjBjYTEzMmFkYWJkMGRmYmI1ZTliYjA2MTUwNmY5ZWQwZjdjZDcyMjdiOWFlNWViYWQ2MjZhODMxYjc0ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UhBQI7IOmpm3WkfMbrTVfgoQowDobRyKev07cYKo_PA)

Great idea! 
I also setup an automation to get notified on price change and it seems like at some point if the price is not updated for certain amount of days it goes to "$0.00" and I get notified.

**Comment by firstof9** [comment]
@brunob45 @JohnyBeGood please see #103 there's a beta with the changes to test if you wouldn't mind.

**Comment by JohnyBeGood** [comment]
> @brunob45 @JohnyBeGood please see #103 there's a beta with the changes to test if you wouldn't mind.

I re-downloaded beta version. Does price of $0.00 needs to change to offline or something else?

**Comment by JohnyBeGood** [comment]
Nevermind. I didn't see that after the re-install it needed a restart.
Now it shows "Unknown"
